### ISSUE TITLE
Error: hbs is not defined

### ISSUE THREAD

**Issue by chubaka** [babiz/express-handlebars-paginate#3]
Hi,

I am using express hanlebars and the following code:
var paginateHelper = require('express-handlebars-paginate');
hbs.handlebars.registerHelper('paginateHelper', paginateHelper.createPagination);

I get the following error:
hbs.handlebars.registerHelper('paginateHelper', paginateHelper.createPagination);
^

ReferenceError: hbs is not defined

Can you help?

**Comment by babiz** [comment]
HI Chubaka,

It says hbs is not defined. Did you define that. 
For example:

``` javascript
    var hbs = exphbs.create({
        defaultLayout: 'main',
        extname: '.html',    
        helpers: handlebarsHelpers,
    });`
```
