### ISSUE TITLE
Breaks the view

### ISSUE THREAD

**Issue by mylastore** [babiz/express-handlebars-paginate#6]
I could see the pagination element but does not render the rest of the view. 
![shot](https://user-images.githubusercontent.com/8906338/31303153-8a03d4b0-aabd-11e7-8b40-f44c206d8600.png)

**Comment by mylastore** [comment]
Now i formatted this way res.render('account/order-history', {orders: orders, pagination: { page: currentPage, limit: limit, totalRows: rows }});

and is not working either currently have the limit to 5 but does not seem to take effect 

Is this suppose to be a completely separe view just for the pagination or it could be a combination for example on my orders saved and pagination all in one view and controller?

![my app](https://user-images.githubusercontent.com/8906338/31303291-d5a064f4-aabf-11e7-83f6-1e7e658cb5d4.png)

**Comment by babiz** [comment]
@mylastore I think there is something wrong your code that renders overview orders. This module only is related to give pagination elements and does not relate to overview part. I see the pagination is coming so the module is working fine but there may be something wrong with your code.

**Comment by mylastore** [comment]
@babiz ah ok that's what I wanted to know, so I have to handle the rendering of the individual chunks of data of each age?

**Comment by babiz** [comment]
Basically, this is how I integrate this in the controllers. 

```javascript
res.render('contacts/index', {
            contacts: contacts.rows,
            pagination: {
                page: req.query.page,
                limit:req.query.limit,
                totalRows: contacts.count
            }
        });
```

Then iterate the contacts object in the view using loop command to show the view. SOmething like this
```javascript
   {{#each contacts as |contact|}}
                    <tr>
                        <td>{{contact.name}}</td>
                        <td>{{contact.organization}}</td>
                        <td>{{contact.email}}</td>
                       ..............
......
```

**Comment by mylastore** [comment]
@babiz I try the  page: req.query.page did not work for me but go it to work this way. Hope it helps someone else. 

![shop](https://user-images.githubusercontent.com/8906338/31361125-991a2530-ad06-11e7-9374-12fbb0cee824.png)
